name: freelance_hub
description: A comprehensive freelancer-client platform built with Flutter and Firebase.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  meta: ^1.16.0
  lints: ^6.0.0

  
  # Firebase dependencies - latest compatible versions
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  
  # Chart dependency
  fl_chart: ^1.1.0
  
  # Utility packages
  intl: ^0.20.2
  image_picker: ^1.0.7
  file_picker: ^10.3.2
  cached_network_image: ^3.3.1
  
  # State management (optional, for complex state)
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # Add assets if needed
  # assets:
  #   - images/
  #   - icons/
  
  # Add fonts if needed
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: fonts/Inter-Regular.ttf
  #       - asset: fonts/Inter-Bold.ttf
  #         weight: 700
